# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        test: [javac8, javac11, javac14, eclipse-oxygen, eclipse-202006, ecj11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml test.${{ matrix.test }}
      env:
        JAVA_HOME: $JAVA_HOME
